# Generated by Django 3.1.3 on 2020-11-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akikaapp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
