# Generated by Django 3.1.3 on 2020-11-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akikaapp', '0004_message_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Akika',
        ),
    ]
